server:
  port: 9010

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8b209.p.ssafy.io:3306/here?serverTimezone=Asia/Seoul
    username: root
    password: B209HERE

notification:
  mattermost:
    enabled: true
    webhook-url: https://meeting.ssafy.com/hooks/yghzwyag6fnmtqwmpoqmufxn6h