server:
  port: 9001
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    default: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


cloud:
  aws:
    credentials:
      accessKey: AKIAYZZXAQTVAKCQ4ZJB
      secretKey: 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
    s3:
      bucket: here-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2