server:
  port: 9001
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: B209HERE
    key-store-type: PKCS12

spring:
  profiles:
    default: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


cloud:
  aws:
    credentials:
      access-key: AKIAYZZXAQTVAKCQ4ZJB
      secret-key: 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
    s3:
      bucket: here-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2