server:
  port: 9011

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: none

test: dev


notification:
  mattermost:
    enabled: true
    webhook-url: https://meeting.ssafy.com/hooks/yghzwyag6fnmtqwmpoqmufxn6h