server:
  port: 9001

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

notification:
  mattermost:
    enabled: true
    webhook-url: https://meeting.ssafy.com/hooks/zqmjek3mi7fgmg4zh5knfu3ndy