package com.ssafy.herenotification.enumeration.response;

public enum HereStatus {
    HERE_SUCCESS_SIGNUP,
    HERE_DUPLICATED_EMAIL,
    HERE_NOT_DUPLICATED_EMAIL,
    HERE_DUPLICATED_NICKNAME,
    HERE_NOT_DUPLICATED_NICKNAME,
    HERE_SUCCESS_FIND_MEMBER,
    HERE_NOT_SUCCESS_FIND_MEMBER,
    HERE_UPDATE_EXP,
    HERE_UPDATE_LEVEL,
    HERE_SUCCESS_FIND_CHARACTER,
    HERE_SUCCESS_CREATE_CHARACTER,
    HERE_SUBMIT_CERTIFICATION,
    HERE_CREATE_NOTIFICATION,
    HERE_FIND_NOTIFICATION,
    HERE_READ_NOTIFICATION,
    HERE_FIND_BD_HISTORY,
    HERE_FIND_STAMP,
    HERE_SEARCH_ORGAN,
}
